name: anthem_assistant
description: A new Flutter project.

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"
  http: ^0.12.0+1
  random_string: ^0.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_anthem_assistant_white.png"
  adaptive_icon_background: "#FFED3E4D"
  adaptive_icon_foreground: "assets/icon_anthem_assistant.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo_anthem_assistant_white.png
    - assets/icon_anthem_assistant.png
